Repository haskell/hackage-server, pull requests merged in 2022-12, with the labels that each got.

#1150 Allow mtl-2.3 and transformers-0.6
  .github/workflows/cabal-mtl-2.3.yml
  hackage-server.cabal
  src/Distribution/Server/Features/Browse.hs
  src/Distribution/Server/Features/Core/Backup.hs
  src/Distribution/Server/Features/Security/Backup.hs
  src/Distribution/Server/Features/Security/State.hs
  src/Distribution/Server/Framework/BackupRestore.hs
  src/Distribution/Server/Util/Markdown.hs
Labels: re: dependencies

#1124 Disable test
  datafiles/templates/Html/maintain.html.st
  datafiles/templates/Html/reports-test.html.st
  exes/BuildClient.hs
  src/Distribution/Server/Features/BuildReports.hs
  src/Distribution/Server/Features/BuildReports/BuildReport.hs
  src/Distribution/Server/Features/BuildReports/BuildReports.hs
  src/Distribution/Server/Features/BuildReports/State.hs
  src/Distribution/Server/Features/Html.hs
Labels: ready-for-merge

#1099 Add captcha for user registration
  .github/workflows/cabal-mtl-2.3.yml
  .github/workflows/haskell-ci.yml
  datafiles/templates/UserSignupReset/SignupRequest.html.st
  hackage-server.cabal
  shell.nix
  src/Distribution/Server/Features/UserSignup.hs
Labels: ready-for-merge

#1140 Add lastVersion in listings (#749)
  datafiles/static/browse.js
  datafiles/templates/Html/browse.html.st
  datafiles/templates/Html/table-interface.html.st
  src/Distribution/Server/Features/Browse.hs
  src/Distribution/Server/Features/Browse/ApplyFilter.hs
  src/Distribution/Server/Features/Browse/Options.hs
  src/Distribution/Server/Features/Html/HtmlUtilities.hs
  src/Distribution/Server/Features/PackageList.hs
Labels: blocked
