Repository haskell/hackage-server, pull requests merged in 2022-04, with the labels that each got.

#1061 Auto-generate more complete CI via haskell-ci
  .github/workflows/ci.yml.deactivated
  .github/workflows/haskell-ci.yml
  .travis.yml
  cabal.haskell-ci
  hackage-server.cabal
Labels: re: CI

#1059 Fix incomplete-record-updates warnings
  src/Distribution/Server/Features/Users.hs
  src/Distribution/Server/Framework/Auth.hs
  src/Distribution/Server/Framework/HappstackUtils.hs
Labels: re: code quality

#1065 Use assert{Bool,Failure} from tasty-hunit
  tests/PackageTestMain.hs
Labels: re: testsuite
